### ISSUE TITLE
HikariCP连接Atlas   初始化异常

### ISSUE THREAD

**Issue by notreami** [Qihoo360/Atlas#119]
JDK版本：Java8
引用包版本
compile('mysql:mysql-connector-java:5.1.38')
compile('org.springframework.boot:spring-boot-starter-jdbc:1.4.0.RELEASE')
compile('org.springframework.data:spring-data-commons:1.4.0.RELEASE')
compile('com.zaxxer:HikariCP:2.4.7')

配置代码
    public HikariDataSource getHikariDataSource(String driverClassName, String jdbcUrl, String userName, String password) {
        HikariConfig config = new HikariConfig();
        config.setDriverClassName(driverClassName);//指定driver的类名，默认从jdbc url中自动探测.
        config.setJdbcUrl(jdbcUrl);//指定JDBC URL
        config.setUsername(userName);//指定用户名
        config.setPassword(password);//指定数据库密码

       addHikariConfig(config);
        HikariDataSource hikariDataSource = new HikariDataSource(config);
        return hikariDataSource;
    }

    private void addHikariConfig(HikariConfig hikariConfig) {
//        hikariConfig.setAllowPoolSuspension(false);//使用Hikari pool时，是否允许连接池暂停，默认为: false
//        hikariConfig.setAutoCommit(true);//指定updates是否自动提交
//        hikariConfig.setCatalog();//指定默认的catalog
        hikariConfig.setConnectionInitSql("SELECT 1");//指定连接被创建，再被添加到连接池之前执行的sql.
        hikariConfig.setConnectionTestQuery("SELECT 1");//指定校验连接合法性执行的sql语句
//        hikariConfig.setConnectionTimeout(30000);//指定连接的超时时间，毫秒单位.缺省:30秒
//        hikariConfig.setDataSourceClassName();//指定数据源的全限定名
//        hikariConfig.setDataSourceJNDI();//指定jndi的地址
//        hikariConfig.setHealthCheckRegistry();//心跳检查注册
//        hikariConfig.setIdleTimeout(600000);//指定连接多久没被使用时，被设置为空闲，默认为10分钟
//        hikariConfig.setInitializationFailFast();//当创建连接池时，没法创建指定最小连接数量是否抛异常
//        hikariConfig.setIsolateInternalQueries();//指定内部查询是否要被隔离，默认为false
//        hikariConfig.setLeakDetectionThreshold();//使用Hikari connection pool时，多少毫秒检测一次连接泄露
        hikariConfig.setMinimumIdle(8);//指定连接维护的最小空闲连接数，当使用HikariCP时指定
        //指定连接池中连接的最大生存时间，毫秒单位.缺省:30分钟，建议设置比数据库超时时长少30秒以上，
        //参考MySQL wait_timeout参数（show variables like '%timeout%';）
//        hikariConfig.setMaxLifetime(1765000);
        //指定连接池最大的连接数，包括使用中的和空闲的连接,缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
        hikariConfig.setMaximumPoolSize(32);//15
//        hikariConfig.setMetricRegistry();
//        hikariConfig.setPoolName();//指定连接池名字
//        hikariConfig.setReadOnly();//当使用Hikari connection pool时，是否标记数据源只读
//        hikariConfig.setRegisterMbeans();//指定Hikari connection pool是否注册JMX MBeans.
//        hikariConfig.setTransactionIsolation();//指定连接的事务的默认隔离级别
//        hikariConfig.setValidationTimeout(SECONDS.toMillis(5));//设定连接校验的超时时间，当使用Hikari connection pool时指定
    }

错误信息
2016-08-16 11:06:12,370 [main] INFO  (HikariDataSource:77) - HikariCP pool HikariPool-0 is starting.
Exception in thread "main" java.lang.RuntimeException: Fail-fast during pool initialization
	at com.zaxxer.hikari.pool.HikariPool.fillPool(HikariPool.java:475)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:159)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:78)
	at com.sankuai.meituan.flight.skupdate.test.MysqlDBTest.main(MysqlDBTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.sql.SQLException: Proxy Warning - Syntax Forbidden Query:set session transaction read write
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
	at com.mysql.jdbc.ConnectionImpl.setReadOnlyInternal(ConnectionImpl.java:5017)
	at com.mysql.jdbc.ConnectionImpl.setReadOnly(ConnectionImpl.java:5010)
	at com.zaxxer.hikari.util.PoolUtilities.setupConnection(PoolUtilities.java:180)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:411)
	at com.zaxxer.hikari.pool.HikariPool.fillPool(HikariPool.java:474)
	... 9 more

Process finished with exit code 1

**Comment by peterxiemin** [comment]
我也碰到类似问题，解决办法是啥？

**Comment by notreami** [comment]
@peterxiemin 
mysql 5.6.*版本引入了一个优化：readOnly（具体这个优化，可以去看MYSQL的官方文档，目的是为了保证一系列的读操作可以看到相同的值）。相应的JDBC规范也引入了一个配置参数 readOnlyPropagatesToServer，该参数描述如下：

readOnlyPropagatesToServer
Should the driver issue appropriate statements to implicitly set the transaction access mode on server side when Connection.setReadOnly() is called? Setting this property to 'true' enables InnoDB read-only potential optimizations but also requires an extra roundtrip to set the right transaction state. Even if this property is set to 'false', the driver will do its best effort to prevent the execution of database-state-changing queries. Requires minimum of MySQL 5.6.
Default: true
Since version: 5.1.35

所以出现这个问题的判断逻辑是先向后台的服务器询问是否支持readOnly优化，切版本是否是5.6.* +，因为，atlas只是一个Proxy，所以在getReadOnlyPropagatesToServer()和versionMeetsMinimum(5, 6, 5)方法会直接转发了请求，所以，修改atlas让其返回低版本的路走不通，那么现在就只能关闭mysql的ReadOnly优化了，所以尝试，在jdbc的连接里加入参数，如下：

jdbc:mysql://host:port/db?readOnlyPropagatesToServer=false


顺带吐槽下 Druid，居然不报错，规范遵守的不积极啊。

**Comment by peterxiemin** [comment]
我的mysql版本是5.6+， jdbc:mysql://host:port/db?readOnlyPropagatesToServer=false 关闭这个配置后果然不报错了，非常感谢，我再仔细研究一下原理
