### ISSUE TITLE
jdbc连接atlas报错

### ISSUE THREAD

**Issue by zengchao1212** [Qihoo360/Atlas#58]
因为是做测试，所以现在读写都是一台机器，版本如下
mysql:mysql-5.6.26
atlas:atlas-2.2.1_x86_64
这几个都在同一台centos 7 上
测试环境在windows上，jdbc版本为5.1.36，直连mysql没问题，连上atlas报错
java.sql.SQLException: Unknown system variable 'language'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2541)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2499)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1432)
	at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:3870)
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3284)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2293)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2079)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)

atlas日志没有错误信息，内容如下
2015-07-29 17:50:48: (message) chassis-unix-daemon.c:138: [angel] we try to keep PID=20888 alive
2015-07-29 17:50:48: (message) mysql-proxy 0.8.2 started - instance: test
2015-07-29 17:50:48: (message) proxy listening on port 0.0.0.0:1234
2015-07-29 17:50:48: (message) added read/write backend: 127.0.0.1:3306
2015-07-29 17:50:48: (message) chassis-event-thread.c:235: starting 2 threads
2015-07-29 17:52:44: (message) chassis-unix-daemon.c:138: [angel] we try to keep PID=20924 alive
2015-07-29 17:52:44: (message) mysql-proxy 0.8.2 started - instance: test
2015-07-29 17:52:44: (message) proxy listening on port 0.0.0.0:1234
2015-07-29 17:52:44: (message) added read/write backend: 127.0.0.1:3306
2015-07-29 17:52:44: (message) added read-only backend: 192.168.193.78:3306
2015-07-29 17:52:44: (message) chassis-event-thread.c:235: starting 2 threads
2015-07-30 08:52:47: (message) chassis-unix-daemon.c:138: [angel] we try to keep PID=12321 alive
2015-07-30 08:52:47: (message) mysql-proxy 0.8.2 started - instance: test
2015-07-30 08:52:47: (message) proxy listening on port 0.0.0.0:1234
2015-07-30 08:52:47: (message) added read/write backend: 127.0.0.1:3306
2015-07-30 08:52:47: (message) added read-only backend: 192.168.193.78:3306
2015-07-30 08:52:47: (message) chassis-event-thread.c:235: starting 2 threads
2015-07-30 09:08:24: (message) chassis-unix-daemon.c:138: [angel] we try to keep PID=12390 alive
2015-07-30 09:08:24: (message) mysql-proxy 0.8.2 started - instance: test
2015-07-30 09:08:24: (message) proxy listening on port 0.0.0.0:1234
2015-07-30 09:08:24: (message) added read/write backend: 127.0.0.1:3306
2015-07-30 09:08:24: (message) chassis-event-thread.c:235: starting 2 threads

这个atlas对mysql有没有版本要求，或者是基于哪个版本开发的

**Comment by zengchao1212** [comment]
通过调试JDBC源码发现问题根源，直连MYSQL返回的版本是5.6.26,通过atlas返回的版本是5.0.81，如果是5.0，jdbc会查询系统变量“language”，但是事实上我们的版本是5.6,系统中并没有这个变量，所以出错

**Comment by zhuchao-hit** [comment]
你好，可以修改Atlas代码把5.0.81改成5.6.26，5.0.81只是个伪装。
